### ISSUE TITLE
Simple working example with locale other than en?

### ISSUE THREAD

**Issue by rightwork** [globalizejs/globalize-compiler#11]
I'm trying to display a currency other than USD, such as EUR.  To troubleshoot, I started with a simpler example: 

> https://github.com/jquery/globalize/tree/master/examples/globalize-compiler

In package.json, I changed the locale from `en` to `de`:

> ```
> "build": "globalize-compiler -l de -c cldr.json -m messages.json -o compiled-formatters.js app.js"
> ```

In app.js, I changed the locale from `en` to `de`:

> Globalize.locale( "de" );

And, also in app.js, I changed `USD` to `EUR`:

> document.getElementById( "currency" ).textContent = Globalize.formatCurrency( 69900, "EUR" );

For good measure, I also added a `de` entry for the `like` message in messages.json.

Here is the error I receive, below.  Any pointers? 

```
dev@dev:~/globalize/examples/globalize-compiler$ npm run build

> basic-globalize-compiler@ build ./globalize/examples/globalize-compiler
> globalize-compiler -l de -c cldr.json -m messages.json -o compiled-formatters.js app.js


./globalize/examples/globalize-compiler/node_modules/globalize/node_modules/cldrjs/dist/cldr.js:164
            return cldr.get( "supplemental/likelySubtags/und" ).split( sep );
                                                                ^
TypeError: Cannot call method 'split' of undefined
    at coreLikelySubtags (./globalize/examples/globalize-compiler/node_modules/globalize/node_modules/cldrjs/dist/cldr.js:164:56)
    at Cldr.init (./globalize/examples/globalize-compiler/node_modules/globalize/node_modules/cldrjs/dist/cldr.js:605:19)
    at Cldr.init (./globalize/examples/globalize-compiler/node_modules/globalize/node_modules/cldrjs/dist/cldr/event.js:554:13)
    at Cldr.init (./globalize/examples/globalize-compiler/node_modules/globalize/node_modules/cldrjs/dist/cldr/supplemental.js:92:13)
    at new Cldr (./globalize/examples/globalize-compiler/node_modules/globalize/node_modules/cldrjs/dist/cldr.js:547:8)
    at alwaysCldr (./globalize/examples/globalize-compiler/node_modules/globalize/dist/globalize.js:286:55)
    at Function.Globalize.locale (./globalize/examples/globalize-compiler/node_modules/globalize/dist/globalize.js:370:15)
    at Object.compileExtracts (./globalize/examples/globalize-compiler/node_modules/globalize-compiler/lib/compile-extracts.js:53:12)
    at Object.<anonymous> (./globalize/examples/globalize-compiler/node_modules/globalize-compiler/bin/globalize-compiler.js:82:28)
    at Module._compile (module.js:456:26)

npm ERR! basic-globalize-compiler@ build: `globalize-compiler -l de -c cldr.json -m messages.json -o compiled-formatters.js app.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the basic-globalize-compiler@ build script.
npm ERR! This is most likely a problem with the basic-globalize-compiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     globalize-compiler -l de -c cldr.json -m messages.json -o compiled-formatters.js app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls basic-globalize-compiler
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.2.0-23-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! cwd ./globalize/examples/globalize-compiler
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     ./globalize/examples/globalize-compiler/npm-debug.log
npm ERR! not ok code 0
```

**Comment by rightwork** [comment]
Dang it.  I forgot to remove the `-c cldr.json` argument from the `npm run build` command line in `package.json`.  Once I did that it worked fine.  Sorry!
